---
title: "Regulamin Zajęć"
output:
  pdf_document: default
  word_document: default
header-includes: \usepackage[polish]{babel}
---

Przedmiot: Pracownia dyplomowa 1

Rodzaj zajęć: seminarium dyplomowe

Kierunek: Informatyka

Specjalność: informatyka ogólna/inżynieria systemów informatycznych

Poziom studiów: studia pierwszego stopnia

Rodzaj studiów: studia stacjonarne/niestacjonarne

Rok i semestr: rok III, semestr szósty

Rok akademicki: 2018/2019

Prowadzący: dr Piotr Jastrzębski, piotr.jastrzebski@uwm.edu.pl, piojas@matman.uwm.edu.pl

Liczba punktów ECTS: 2,5

## 1. Wymagana forma uczestnictwa w zajęciach
Pierwsze spotkanie będzie zajęciami organizacyjnymi. W kolejnych studenci pojedynczo będą prezentować referaty na przygotowane wcześniej tematy. Pozostałe zajęcia będą wykorzystane na indywidualne konsultacje związane z przygotowaniem pracy inżynierskiej.

##2. Tematyka seminarium.
Programowanie gier w Unity 3D w oparciu o język C#.

##3. Cele kształcenia.

1. Celem przedmiotu jest zaznajomienie studentów z wymogami pracy inżynierskiej, udzielanie wskazówek przy pisaniu pracy oraz wsparcie merytoryczne prowadzące do ukończenia pracy.

##4. Efekty kształcenia.

**Wiedza**

W1 - doskonale orientuje się w klasyfikacji i przeznaczeniu podstawowych technik i oprogramowania dotyczących tematu swej pracy dyplomowej.

**Umiejętności**

U1 - posiada umiejętności praktyczne w tworzeniu rozwiązań, aplikacji lub oprogramowania w oparciu o nowoczesne narzędzia programowe związane z tematyką pracowni dyplomowej.

**Kompetencje społeczne**

K1 - zna ograniczenia własnej wiedzy, rozumie potrzebę dalszego pogłębienia i unowocześniania wiedzy.

## 5. Literatura.

1. J. G. Bond, Projektowanie gier przy użyciu środowiska Unity i języka C#. Od pomysłu do gotowej gry. Wydanie II, Wyd. Helion, 2018.

2. E. Ross, J. Ross, Unity i C#. Podstawy programowania gier, Wyd. Helion, 2018.

3. M. Geig, Unity. Przewodnik projektanta gier, Wyd. Helion, 2015.

4. J. Hocking, Unity w akcji, Wyd. Helion, 2017.

5. F. Sapio, Unity. Przepisy na interfejs gry, Wyd. Helion, 2016.

## 6. Sposób bieżącej kontroli wyników nauczania.

Brak.

## 7. Referat.
W trakcie seminarium każdy student ma za zadanie przygotować i wygłosić referat na wyznaczony temat przez prowadzącego zajęcia. Ocena za referat będzie uwzględniała składowe:

* przygotowanie merytoryczne - 70%.
* sposób prezentacji - 15%.
* właściwe zarządzanie czasem - 15%.

## 8. Zasady usprawiedliwiania nieobecności na zajęciach.
Nieobecności na zajęciach będą usprawiedliwiane na podstawie usprawiedliwień pisemnych
poświadczonych odpowiednim podpisem (ew. brak podpisu musi wynikać z przepisów szczególnych). Informacja o studentach, których liczba nieusprawiedliwionych nieobecności przekracza 3, zostanie przesłana do odpowiedniego dziekanatu.

## 9. Zasada ustalania oceny końcowej zaliczenia przedmiotu.
Zaliczenie ćwiczeń będzie przyznane tym uczestnikom zajęć, którzy otrzymają pozytywną ocenę za przygotowany referat oraz zgodnie z odrębnymi przepisami dopełnią formalności ze zgłoszeniem tematu pracy inżynierskiej do dnia 9.06.2019. W wyjątkowych sytuacjach termin może zostać wydłużony do maksymalnego terminu na wpisanie ocen w systemie USOS.

## 10. Konsultacje.
Aktualne terminy konsultacji dostępne są w systemie USOS i na stronie prowadzącego zajęcia.










